

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\UserLoginFormAuthenticator
            custom_authenticators:
                - App\Security\UserLoginFormAuthenticator  # User authentication
                - App\Security\LoginFormAuthenticator  # User authentication

            form_login:
                login_path: home_signin  # Your existing login route
                check_path: home_signin  # Where the login form submits
                default_target_path: app_2fa_verify  # Redirect to 2FA after successful login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home  # Redirect users to homepage after logout


    access_control:

        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_ADMIN }