#security:
#    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
#
#    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: email
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            lazy: true
#            provider: app_user_provider
#            entry_point: App\Security\LoginFormAuthenticator
#            custom_authenticators:
#                - App\Security\LoginFormAuthenticator
#            logout:
#                path: app_logout
#                target: app_dashboard_signin
#
#    access_control:
#        - { path: ^/dashboard/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/dashboard/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/dashboard, roles: ROLE_ADMIN }

# config/packages/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
#            entry_point: App\Security\LoginFormAuthenticator
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_dashboard_signin

    access_control:
        # Public access to signin and signup pages
        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }

        # Restrict access to the dashboard to authenticated users
        - { path: ^/dashboard, roles: ROLE_ADMIN }