#
#security:
#    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
#
#    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: email
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#
#            lazy: true
#            provider: app_user_provider
#            entry_point: App\Security\UserLoginFormAuthenticator
#            custom_authenticators:
#                - App\Security\UserLoginFormAuthenticator  # User authentication
#                - App\Security\LoginFormAuthenticator
#            logout:
#                path: app_logout
#                target: app_home  # Redirect users to homepage after logout
#            two_factor:
#                auth_form_path: 2fa_login
#                check_path: 2fa_login_check
#                default_target_path: app_home
#
#    access_control:
#        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
#        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }
#        - { path: ^/dashboard, roles: ROLE_ADMIN }
#
#



security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\UserLoginFormAuthenticator
            custom_authenticators:
                - App\Security\UserLoginFormAuthenticator  # User authentication
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home  # Redirect users to homepage after logout
            two_factor:
                auth_form_path: 2fa_login          # Route to the 2FA form
                check_path: 2fa_login_check        # Route to validate the 2FA code
                default_target_path: app_home       # Route to redirect after successful 2FA
#                always_use_default_target_path: true

    access_control:
        - { path: ^/2fa/login, roles: PUBLIC_ACCESS }  # Allow access to the 2FA login form
        - { path: ^/2fa, roles: PUBLIC_ACCESS }              # Allow access to the 2FA setup page for fully authenticated users
        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
    #                - { path: ^/, roles: IS_AUTHENTICATED_FULLY }                  # Require full authentication for all other routes