
#security:
#    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
#
#    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\User
#                property: email
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            lazy: true
#            provider: app_user_provider
#            entry_point: App\Security\LoginFormAuthenticator
#            custom_authenticators:
#                - App\Security\LoginFormAuthenticator
#                - App\Security\UserLoginFormAuthenticator
#            logout:
#                path: app_logout
#                target: app_dashboard_signin
#
#
#    access_control:
#        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
#        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }
#
#        - { path: ^/dashboard, roles: ROLE_ADMIN }




security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\UserLoginFormAuthenticator
            custom_authenticators:
                - App\Security\UserLoginFormAuthenticator  # User authentication
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home  # Redirect users to homepage after logout
#
#        admin:
#            lazy: true
#            provider: app_user_provider
##            entry_point: App\Security\LoginFormAuthenticator
#            custom_authenticators:
#                - App\Security\LoginFormAuthenticator
#            logout:
#                path: app_logout
#                target: app_dashboard_signin  # Redirect admins to dashboard login after logout

    access_control:
        - { path: ^/dashboard/signin, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard/signup, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
